name: cose così
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151513'
    - '#7b7368'
    - '#40c2c2'
    - '#ffffff'
    - '#46eedd'
  brandStrength: 0
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0
purpose: []
