name: cose così
favicon: null
layout_spectrum: 0.3801936178933829
typography_spectrum: 0.8135666029993445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4625910110771656
  lightness: 0.6394772476051003
  saturation: 0.6871988298371434
  rhythmicContrast: 0.298603123286739
purpose: []
